name: Build for reMarkable
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: make image
      - name: Build
        run: make build
      - name: Package resources
        if: startsWith(github.ref, 'refs/tags/')
        run: tar -C ./build/netsurf -cvzf nsfb.tar.gz resources/ nsfb
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            LICENSE
            nsfb.tar.gz
            build/netsurf/nsfb
            
